# Generated by Django 3.0.2 on 2020-01-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200110_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='member',
        ),
        migrations.AddField(
            model_name='teammember',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Post'),
        ),
    ]
