# Generated by Django 3.0.2 on 2020-01-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200114_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='blog.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19),
        ),
    ]
