# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-16 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200116_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('caption', models.CharField(blank=True, max_length=70, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Image')),
            ],
        ),
    ]
