# Generated by Django 3.0.2 on 2020-01-21 00:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200121_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular post', primary_key=True, serialize=False),
        ),
    ]
