# Generated by Django 3.0.2 on 2020-01-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200121_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumpost',
            name='text',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
